pConsumption <- read.table("exdata_data_household_power_consumption/household_power_consumption.txt", comment.char="", quote='\"', na.strings="?", check.names=FALSE, 
                            header=TRUE, dec=".", sep=";")
pConsumption$Date <- as.Date(pConsumption$Date, format="%d/%m/%Y")
pCByDate <- subset(pConsumption, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
dt <- strptime(paste(pCByDate$Date, pCByDate$Time, sep=" "), "%Y-%m-%d %H:%M:%S")  
sM1 <- as.numeric(pCByDate$Sub_metering_1) 
sM2 <- as.numeric(pCByDate$Sub_metering_2) 
sM3 <- as.numeric(pCByDate$Sub_metering_3) 
gAPower <- as.numeric(pCByDate$Global_active_power) 
gRPower <- as.numeric(pCByDate$Global_reactive_power) 
vol <- as.numeric(pCByDate$Voltage) 

png("plot4.png", width=500, height=500) 
par(mfrow = c(2, 2))  
plot(dt, gAPower, type="l", xlab="", ylab="Global Active Power", cex=0.2) 
plot(dt, vol, type="l", xlab="datetime", ylab="Voltage") 
plot(dt, sM1, type="l", ylab="Energy Submetering", xlab="") 
lines(dt, sM2, type="l", col="red") 
lines(dt, sM3, type="l", col="blue") 
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o") 
plot(dt, gRPower, type="l", xlab="datetime", ylab="Global_reactive_power") 
dev.off() 